### ISSUE TITLE
Interace  vpn_irr not found.

### ISSUE THREAD

**Issue by shinji62** [Dmitriusan/docker-softether-vpn-client#1]
Hi,

I am not sure where this interface " vpn_irr" is coming from to be honest.
I got the error when starting the container
```
The SoftEther VPN Client service has been started.
Internet Systems Consortium DHCP Client 4.3.3
Copyright 2004-2015 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Cannot find device "vpn_irr"
/sbin/dhclient-script: 40: /etc/dhcp/dhclient-exit-hooks.d/debug: source: not found
Error getting hardware address for "vpn_irr": No such device

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging..

exiting.
```

**Comment by shinji62** [comment]
Any help is welcome.

Thanks.

**Comment by Dmitriusan** [comment]
@shinji62 ,
that's my bad. I should make interface name configurable in any way
The error is produced by ```dhclient -d vpn_irr``` command at the end of a Dockerfile.
You should either change vpn interface name at vpn_client.config to vpn_irr, or change the last line of a Dockerfile to match your interface name. I'll probably update Dockerfile on weekend to be more flexible

In my vpn_client.config interface name is defined like
        declare UnixVLan
        {
                declare irr
                {
                        bool Enabled true
                        string MacAddress 00-DC-AC-68-4E-78
                }
        }

**Comment by Dmitriusan** [comment]
Updated code & readme
